### ISSUE TITLE
Request: TTF font format

### ISSUE THREAD

**Issue by nagyrobi** [arallsopp/hass-hue-icons#105]
Is there a way to convert/release this package in a TTF font file, just like MDI icons are? This would allow us to use them easily in [openHASP](https://haswitchplate.github.io/openHASP-docs/).

**Comment by arallsopp** [comment]
I'll look into that. If you can point me at any reference material you have that would be great. Potentially there's a web site somewhere that'll let me upload the svgs and create a font. 

Thanks for the suggestion.

**Comment by nagyrobi** [comment]
Maybe like https://github.com/Templarian/MaterialDesign-Font-Build

**Comment by arallsopp** [comment]
Thanks. Will read up on that.

**Comment by nagyrobi** [comment]
Some kind of script would be nice which could be hooked into Github's actions menu and would generate the TTF automatically whenever you commit a new change :)

**Comment by arallsopp** [comment]
I may need your help in the future to test this. If I can rig up a few glyphs over the next few days, might you be able to let me know if it works?

**Comment by nagyrobi** [comment]
Sure!!!

**Comment by nagyrobi** [comment]
Also https://mediatemple.net/blog/design-creative/creating-implementing-icon-font-tutorial/

**Comment by arallsopp** [comment]
Good find! Can you tell me if these work? I'll have to find out how we avoid remapping the entire thing every time.

[icomoon.zip](https://github.com/arallsopp/hass-hue-icons/files/7612507/icomoon.zip)

**Comment by arallsopp** [comment]
...and if they did work, here's the full set as it stands today.
[hass-hue-icons-v1.0.zip](https://github.com/arallsopp/hass-hue-icons/files/7612543/hass-hue-icons-v1.0.zip)

**Comment by nagyrobi** [comment]
This is awesome!
![kép](https://user-images.githubusercontent.com/1550668/143763918-c4a76acb-cc33-435f-9c78-fe58f9f43308.png)
Works with openHASP (alpha-development test version) out of the box!
How cool it would be if you could release this with every update!

**Comment by arallsopp** [comment]
Excellent. Ok. I don't have a build process that can accommodate this yet, but I will look to update it with every few releases.  The pace of icon requests has slowed a little now, as I think most of them are in already. I don't think I should distribute the font with the main release, as most people won't be using it. 

Do you install via hacs? what's your process for getting notification of an update? How do you install? Would a link on the home page work? If we can get this right, we can document for everyone. 

Cheers!

**Comment by nagyrobi** [comment]
I installed your repo via HACS, so I do get notified when you have an update.

**Comment by arallsopp** [comment]
Ok. I'll add a section to the read me that links to the ttf zip and samples. I'll have to experiment with icomoon to check that the existing glyphs don't get remapped when I upload new mappings. Might be necessary for me to create an svg font locally to track glyphs and icons, but hopefully all will be ok.

**Comment by nagyrobi** [comment]
You could also try https://fontello.com/ (See doc https://github.com/fontello/fontello/wiki/How-to-save-and-load-projects) maybe it's easier.

**Comment by arallsopp** [comment]
That make routine looks good. I may port across. If I do, I expect all of the glyphs will change, but hopefully remain static ever after. I'll comment here if that proves workable.

**Comment by arallsopp** [comment]
For now, I've just put a one liner into the readme for OpenHASP users, and linked it to a version controlled zip file that I've just updated with the new icons. Hopefully the glyphs haven't changed(?). If they're preserved between versions, I'll just keep updating it manually ever few releases.

Oh, and on a slighly sour note, I don't suppose you'll get so far with elax46 and the custom brand icons. I'm afraid they're an icon thief, repeatedly stealing icons from others repos without crediting them. They shadowed this repo since its creation, ripping about 150 icons from the docs folder, removing the author tags, and breaching the license by attempting to charge for the icons, and refusing to credit me as the creator. After a bit of community pressure, they eventually added a line of thanks in their readme, but I note that's gone now.

**Comment by nagyrobi** [comment]
> For now, I've just put a one liner into the readme for OpenHASP users, and linked it to a version controlled zip file that I've just updated with the new icons. Hopefully the glyphs haven't changed(?). If they're preserved between versions, I'll just keep updating it manually ever few releases.

Thank you.


> Oh, and on a slighly sour note, I don't suppose you'll get so far with elax46 and the custom brand icons. I'm afraid they're an icon thief, repeatedly stealing icons from others repos without crediting them. They shadowed this repo since its creation, ripping about 150 icons from the docs folder, removing the author tags, and breaching the license by attempting to charge for the icons, and refusing to credit me as the creator. After a bit of community pressure, they eventually added a line of thanks in their readme, but I note that's gone now.

That's a shame. I noticed similarity but didn't realize that it's 100% ripped.

**Comment by arallsopp** [comment]
Hey, no problem. The risk of open source is that others will abuse it, but that doesn't outweigh the benefits of creating it. I'm not going to let one bad apple ruin it for all of us. 

The theft is more recognisable for me, because I drew all of the custom icons myself. They don't exist anywhere else. The hue developer pack icons are comparatively easily found, but the custom set only exist in response to community requests made here. 

It's a pity, but hey, let's not let the bad stuff distract us.

**Comment by arallsopp** [comment]
Closing for now. If I forget to keep the font updated, please reopen :)

**Comment by arallsopp** [comment]
Updated font for icons added up to v.1.2.3
