### ISSUE TITLE
Hue Signe Floor Light

### ISSUE THREAD

**Issue by davislp** [arallsopp/hass-hue-icons#17]
_If there is a specific hue fixture or bulb that you want an icon for, let me know and I will try to create it for you and add it to this pack._

**What is the specific model of hue fixture/bulb that you want an icon for**
Hue Signe Floor Light

Be as specific as you can, as Philips often seem to have product family names where multiple variants exist under the same description.

**Provide a URL that points to an image of this fixture/bulb**
https://www.philips-hue.com/en-us/p/hue-white-and-color-ambiance-signe-floor-light/4080248U9

Preferably Philips' photography, as they use a consistent angle.

**Additional context**

Add any other context for your icon request here.
Thanks.

**Comment by arallsopp** [comment]
On it…. The light is quite tall, so I might try it focussing on the base. Let’s see.

**Comment by davislp** [comment]
I really appreciate it. Thank you.

**Comment by arallsopp** [comment]
Would this kind of thing work for you?

![image](https://user-images.githubusercontent.com/2462104/127933982-872b2a85-b931-4ca9-93c8-73511bfaf63b.png)

**Comment by davislp** [comment]
Absolutely! Again, I really appreciate you doing this.

**Comment by arallsopp** [comment]
Its in v.1.0.37. Its come out a little heavy in the dash, so I might rework.

**Comment by davislp** [comment]
No worries.

**Comment by arallsopp** [comment]
(Reworked it)

| Icon | Name |
| :--- | :--- |
![hue:signe](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/signe.svg)| hue:signe |

**Comment by davislp** [comment]
I think it looks great.

**Comment by arallsopp** [comment]
Hey @davislp.

Just to let you know, I'm going to be stopping development effort on this for a while, as my work is being stolen by [another repo](https://github.com/elax46/custom-brand-icons/) without permission, in breach of the CC license, and without any attempt to give credit to the original author or those who've helped me.

This project has always been offered as free to use, and for the benefit of the home assistant community rather than any individual. More than half of this library is the 80 or so original icons I've created, drawn and gifted to the home assistant community. Those icons are all original works, driven by requests from people like you, taken on as a willing task, and shared here on a non commercial basis for all who want them.

It felt good to give back, and the work was a reward in itself, but finding the icons I'm creating being offered elsewhere, proffered up alongside a request for paypal donations to support their creation is really not in the spirit of the community. 

The whole experience has left a bad taste in my mouth, and I'll be stepping away for some time.

Cheers, and thanks for your interest.

Andy.

**Comment by arallsopp** [comment]
Howdo @davislp,

Just to let you know, I've just added new icons for the signe gradient versions. Having done that, I've learned a bit more about making icons so might well revisit your signe at some point soon. Until then signe-gradient-floor might be a good match for you.

| Icon | Name |
| :--- | :--- |
| ![hue:signe-gradient-floor](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/signe-gradient-floor.svg)| hue:signe-gradient-floor|
| ![hue:signe-gradient-table](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/signe-gradient-table.svg)| hue:signe-gradient-table|

**Comment by arallsopp** [comment]
That's a better solution.
![image](https://user-images.githubusercontent.com/2462104/131993933-585378bb-dc16-44de-9cc3-752fbc240fd9.png)

Adding this into the next version:

| Icon | Name |
| :--- | :--- |
| ![hue:signe](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/signe.svg)| hue:signe|

**Comment by arallsopp** [comment]
OK. That's in v.1.0.76. Glad to have lost the old 'is it a toilet brush?' icon 🤣
