### ISSUE TITLE
Icon Request [Sultan - Hung & Groups]

### ISSUE THREAD

**Issue by keshirkey** [arallsopp/hass-hue-icons#172]
**What is the specific model of hue fixture/bulb that you want an icon for**

Sultan E26

**Provide a URL that points to an image of this fixture/bulb**

(https://www.philips-hue.com/en-us/p/hue-white-ambiance-1-pack-e26/046677548490)

**Additional context**

I'm interested in the hung version of the sultan bulb icon, as well as group icons for the upward-facing and downward-facing sultan bulbs. Thanks!

**Comment by arallsopp** [comment]
Got you. Ok. Will jump to that next. Thanks for the suggestion

**Comment by arallsopp** [comment]
They're coming. I'll bundle them with your other requests, but preview:
<img width="863" alt="image" src="https://user-images.githubusercontent.com/2462104/169887042-00b7f7a8-6d6b-4bd1-952f-778692423388.png">


For the upward-facing group, I'd probably use:
| Icon | Name | Aliases |
| :--- | :--- | :--- | 
| ![hue:bulb-group](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/svgs/bulb-group.svg)| hue:bulb-group | sultan

**Comment by arallsopp** [comment]
New additions to come in the next release:

| Icon | Name |
| :--- | :--- |
| ![hue:bulb-sultan-hung](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-sultan-hung.svg)| hue:bulb-sultan-hung|
| ![hue:bulb-group-sultan-hung](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-sultan-hung.svg)| hue:bulb-group-sultan-hung|

**Comment by arallsopp** [comment]
Thanks again, @keshirkey. 

Your combinations will be in release [v.1.2.31](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.31). Give me a few minutes and that release will be live. I've also tagged the sultan's with e26 so that you can better find them.


### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 363 custom icons has been driven by a community request just like yours, and stars help people find this repo.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?
