### ISSUE TITLE
Hue Smart Plug

### ISSUE THREAD

**Issue by HunterX86** [arallsopp/hass-hue-icons#18]
_If there is a specific hue fixture or bulb that you want an icon for, let me know and I will try to create it for you and add it to this pack._

**What is the specific model of hue fixture/bulb that you want an icon for**
Hue Smart Plug

Be as specific as you can, as Philips often seem to have product family names where multiple variants exist under the same description.

**Provide a URL that points to an image of this fixture/bulb**
![hue smart plug](https://user-images.githubusercontent.com/1310016/127921905-57be500e-5189-4927-8700-13f836c9bf25.png)

Preferably Philips' photography, as they use a consistent angle.
https://www.assets.signify.com/is/image/PhilipsLighting/22eddadf3fe744a6b26aaa380084c3d8?wid=1500&hei=1125&qlt=82

**Additional context**

Add any other context for your icon request here.

**Comment by arallsopp** [comment]
Thanks. Will take a look. Guess there'll be a few variants on this based upon locale. I'll see if there's something that might catch all.

**Comment by arallsopp** [comment]
Am adding the hue plug icon they use in the iOS app

![image](https://user-images.githubusercontent.com/2462104/127935833-295aa7b1-33ea-49da-9cfa-57ef36e97238.png)

Will also look to make locale specific one that matches your request.

**Comment by arallsopp** [comment]
EU and UK variants as illustrated below will be in the next version. I'm not too familiar with the eu plug, so please re-open if this isn't a good image.

 ![image](https://user-images.githubusercontent.com/2462104/127938724-3a493a3c-1ae6-407c-b110-2edde4dce1aa.png)
![image](https://user-images.githubusercontent.com/2462104/127938759-c4f4b895-9240-4c33-ade1-287707e90c38.png)

**Comment by arallsopp** [comment]
Added socket-eu, as the plug wasn't very easy to read.

| Icon | Name |
| :--- | :--- |
![hue:socket-eu](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/socket-eu.svg)| hue:socket-eu |

**Comment by arallsopp** [comment]
Hey @HunterX86 .

Just to let you know, I'm going to be stopping development effort on this for a while, as my work is being stolen by [another repo](https://github.com/elax46/custom-brand-icons/) without permission, in breach of the CC license, and without any attempt to give credit to the original author or those who've helped me.

This project has always been offered as free to use, and for the benefit of the home assistant community rather than any individual. More than half of this library is the 80 or so original icons I've created, drawn and gifted to the home assistant community. Those icons are all original works, driven by requests from people like you, taken on as a willing task, and shared here on a non commercial basis for all who want them.

It felt good to give back, and the work was a reward in itself, but finding the icons I'm creating being offered elsewhere, proffered up alongside a request for paypal donations to support their creation is really not in the spirit of the community. 

The whole experience has left a bad taste in my mouth, and I'll be stepping away for some time.

Cheers, and thanks for your interest.

Andy.
