### ISSUE TITLE
Wellner Table Lamp

### ISSUE THREAD

**Issue by ACrazyConcept** [arallsopp/hass-hue-icons#19]
_If there is a specific hue fixture or bulb that you want an icon for, let me know and I will try to create it for you and add it to this pack._

**What is the specific model of hue fixture/bulb that you want an icon for**

Philips Hue White Ambiance Wellner Dimmable LED Smart Table Lamp.

**Provide a URL that points to an image of this fixture/bulb**

https://www.philips-hue.com/de-de/p/hue-white-ambiance-tischleuchte-wellner/4440156P6

**Additional context**

No.

**Comment by arallsopp** [comment]
Thanks for this @ACrazyConcept. I've not seen that model before. Looks like a straightforward shape so should get to this later today.

**Comment by ACrazyConcept** [comment]
No problem. Maybe even too simple a shape to make recognisable :) but looking forward to see it.

**Comment by arallsopp** [comment]
Closed in release v.1.0.42

Added wellner and wellner-solid. Thanks @ACrazyConcept.

| Icon | Name |
| :--- | :--- |
| ![hue:wellner-solid](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/wellner-solid.svg)| hue:wellner-solid |
| ![hue:wellner](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/wellner.svg)| hue:wellner |

**Comment by ACrazyConcept** [comment]
Looks good! Thanks. Well done.

**Comment by arallsopp** [comment]
Hey @ACrazyConcept.

Just to let you know, I'm going to be stopping development effort on this for a while, as my work is being stolen by [another repo](https://github.com/elax46/custom-brand-icons/) without permission, in breach of the CC license, and without any attempt to give credit to the original author or those who've helped me.

This project has always been offered as free to use, and for the benefit of the home assistant community rather than any individual. More than half of this library is the 80 or so original icons I've created, drawn and gifted to the home assistant community. Those icons are all original works, driven by requests from people like you, taken on as a willing task, and shared here on a non commercial basis for all who want them.

It felt good to give back, and the work was a reward in itself, but finding the icons I'm creating being offered elsewhere, proffered up alongside a request for paypal donations to support their creation is really not in the spirit of the community. 

The whole experience has left a bad taste in my mouth, and I'll be stepping away for some time.

Cheers, and thanks for your interest.

Andy.

**Comment by ACrazyConcept** [comment]
I am very sorry to hear that. I hope it can somehow be solved. But thanks for your work so far.
