### ISSUE TITLE
Philips Hue Aurelle Rectangle 120x30

### ISSUE THREAD

**Issue by twelve-cgn** [arallsopp/hass-hue-icons#20]
Philips Hue Aurelle Rectangle
https://www.philips-hue.com/de-de/p/hue-white-ambiance-rechteckige-aurelle-panelleuchte/3216331P6

**Additional context**

The square variant (hue:ceiling-square) still exists, but i need the rectangle one.

Great job.

**Comment by arallsopp** [comment]
See release 1.0.43.

I've based it upon the device class rather than make it device specific, as that matches better with the existing ceiling square.

See new hue:ceiling-rect below, alongside existing ceiling-square


| Icon | Name | 
| :--- | :--- | 
| ![hue:ceiling-rect](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-rect.svg)| hue:ceiling-rect |
| ![hue:ceiling-square](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/svgs/ceiling-square.svg)| hue:ceiling-square |

Feel free to re-open if this doesn't work for you. The dimensions aren't 120x30 (closer to 60x30) but it is a rectangle :)

**Comment by twelve-cgn** [comment]
Wow, that's fast. Thank you.

**Comment by arallsopp** [comment]
Hey @twelve-cgn.

Just to let you know, I'm going to be stopping development effort on this for a while, as my work is being stolen by [another repo](https://github.com/elax46/custom-brand-icons/) without permission, in breach of the CC license, and without any attempt to give credit to the original author or those who've helped me.

This project has always been offered as free to use, and for the benefit of the home assistant community rather than any individual. More than half of this library is the 80 or so original icons I've created, drawn and gifted to the home assistant community. Those icons are all original works, driven by requests from people like you, taken on as a willing task, and shared here on a non commercial basis for all who want them.

It felt good to give back, and the work was a reward in itself, but finding the icons I'm creating being offered elsewhere, proffered up alongside a request for paypal donations to support their creation is really not in the spirit of the community. 

The whole experience has left a bad taste in my mouth, and I'll be stepping away for some time.

Cheers, and thanks for your interest.

Andy.
