### ISSUE TITLE
Group of hue lights icon

### ISSUE THREAD

**Issue by thijselblaso** [arallsopp/hass-hue-icons#22]
I'm using a default icon for 'Alle lampen". See the second picture. It would be nice to have a matching icon for a group of hue lights. 

<img width="562" alt="Screenshot 2021-08-10 at 10 36 42" src="https://user-images.githubusercontent.com/38098396/128835658-38583bd5-baba-4b75-8fbd-9f4e144120af.png">

<img width="179" alt="Screenshot 2021-08-10 at 10 36 48" src="https://user-images.githubusercontent.com/38098396/128835670-24402713-79b0-42cd-aef9-1ba58e96cba7.png">
This is a default ha icon.

**Comment by arallsopp** [comment]
Which hue bulb family in particular would you like? Retrolamp? A set of spot lights?

**Comment by thijselblaso** [comment]
It would be nice to have a group of three different lights. Like bulb-classic, bulb-filament-alt, and bulb-spot together in one icon. But I'm not sure if that looks okay all together. So an icon with three of the bulb-classic is already perfect for me.

**Comment by arallsopp** [comment]
It gets a bit muddied with three. I've added a series of groups to release 1.0.45. If you need a mix of bulbs, I can add a few more, but take a look :)

**Comment by arallsopp** [comment]
New combination bulb groups added in 1.0.46. Closing this request:

Icon | Name 
| :--- | :--- |
| ![hue:bulb-group-filament-candle](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-filament-candle.svg)| hue:bulb-group-filament-candle |
| ![hue:bulb-group-filament-filament-alt](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-filament-filament-alt.svg)| hue:bulb-group-filament-filament-alt |
|  ![hue:bulb-group-filament-spot](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-filament-spot.svg)| hue:bulb-group-filament-spot |
| ![hue:bulb-group-filament-sultan](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-filament-sultan.svg)| hue:bulb-group-filament-sultan |

**Comment by arallsopp** [comment]
Hey @thijselblaso.

Just to let you know, I'm going to be stopping development effort on this for a while, as my work is being stolen by [another repo](https://github.com/elax46/custom-brand-icons/releases) without permission, in breach of the CC license, and without any attempt to give credit to the original author or those who've helped me.

You'll doubltess recognise the groups we created together [here](https://github.com/elax46/custom-brand-icons/releases/tag/1.0.14).

This project has always been offered as free to use, and for the benefit of the home assistant community rather than any individual. More than half of this library is the 80 or so original icons I've created, drawn and gifted to the home assistant community. Those icons are all original works, driven by requests from people like you, taken on as a willing task, and shared here on a non commercial basis for all who want them.

It felt good to give back, and the work was a reward in itself, but finding the icons I'm creating being offered elsewhere, proffered up alongside a request for paypal donations to support their creation is really not in the spirit of the community. 

The whole experience has left a bad taste in my mouth, and I'll be stepping away for some time.

Cheers,

Andy.

**Comment by thijselblaso** [comment]
Hi Andy,

I don't know what to say. I hate this kind of thing when people do this
with no shame. Did you already try to contact the guy that steals all of
your work? Or place an issue in this repo with the explanation that this
guy steals all your shit?

If I can do anything let me know!

Kind regards,

Thijs
