### ISSUE TITLE
Hue Liane Wall light

### ISSUE THREAD

**Issue by damtjern** [arallsopp/hass-hue-icons#23]
https://www.philips-hue.com/en-gb/p/hue-white-and-colour-ambiance-liane-wall-light/4090231P9

Hue Liane Wall light

**Comment by arallsopp** [comment]
Hello. Thanks for raising this. 

Liane is a very long thin lamp, which makes it hard to fit as an Icon. 
![image](https://user-images.githubusercontent.com/2462104/129000281-df5dc6f6-50b2-4ec6-b473-39e6287abd60.png)

I'll come up with an interpretation and post it here. If it works for you, let me know?

**Comment by arallsopp** [comment]
How's this? Had to crop the top bar, as otherwise all you'd see is a vertical line. 🤣 

| Icon | Name |
| :--- | :--- |
| ![hue:liane](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/liane.svg)| hue:liane |

I did the same thing with the signe, so perhaps its ok?
| Icon | Name |
| :--- | :--- |
| ![hue:signe](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/signe.svg)| hue:signe |

**Comment by arallsopp** [comment]
@damtjern: Closing with the latest release. Feel free to re-open this ticket if the icon doesn't suit your needs.

**Comment by damtjern** [comment]
Maybe would be better to cut some of the bottom "thick" part aswell to tell it more apart?
Anyway thanks for this, been missing this one for a while!

**Comment by arallsopp** [comment]
![image](https://user-images.githubusercontent.com/2462104/129032280-a290b10a-a240-4508-969e-afb46f2a985f.png)

Old and new versions side by side. Exaggerated the angle, shortened the height of the wall mount.

**Comment by arallsopp** [comment]
Hey @damtjern.

Just to let you know, I'm going to be stopping development effort on this for a while, as my work is being stolen by [another repo](https://github.com/elax46/custom-brand-icons/releases) without permission, in breach of the CC license, and without any attempt to give credit to the original author or those who've helped me.

You'll doubltess recognise the liane light we created together [here](https://github.com/elax46/custom-brand-icons/releases/tag/1.0.16).

This project has always been offered as free to use, and for the benefit of the home assistant community rather than any individual. More than half of this library is the 80 or so original icons I've created, drawn and gifted to the home assistant community. Those icons are all original works, driven by requests from people like you, taken on as a willing task, and shared here on a non commercial basis for all who want them.

It felt good to give back, and the work was a reward in itself, but finding the icons I'm creating being offered elsewhere, proffered up alongside a request for paypal donations to support their creation is really not in the spirit of the community. 

The whole experience has left a bad taste in my mouth, and I'll be stepping away for some time.

Cheers,

Andy.
