### ISSUE TITLE
HUE Adore Mirror Lamp

### ISSUE THREAD

**Issue by clipse2004** [arallsopp/hass-hue-icons#29]
_If there is a specific hue fixture or bulb that you want an icon for, let me know and I will try to create it for you and add it to this pack._

**HUE Adore Mirror Lamp**

Be as specific as you can, as Philips often seem to have product family names where multiple variants exist under the same description.

**https://www.galaxus.de/de/s14/product/philips-hue-mybathroom-adore-basis-bt-wandleuchte-deckenleuchte-13274763?gclid=Cj0KCQjw6s2IBhCnARIsAP8RfAhT-Fr1Kdr5vV-6DEifGhCIM7qJLv800-S3sIVqKgKf-Q5biy9AL9MaAs9iEALw_wcB&gclsrc=aw.ds **

Preferably Philips' photography, as they use a consistent angle.

**Additional context**
Hey dude i hope you can do a Icon for this Lamp :)

big thanks

Add any other context for your icon request here.

**Comment by arallsopp** [comment]
Nice lamp. I've not seen that one before. Will take a look. Thanks @clipse2004

**Comment by arallsopp** [comment]
Hey @clipse2004. Which of these (top / bottom) works best for you?

The bottom is closer to how the lamp appears, but the top one will probably work better when they're only 24px high. 

![image](https://user-images.githubusercontent.com/2462104/129116028-4325111a-8bbf-48d4-8e06-8cb8de8b7f04.png)

**Comment by arallsopp** [comment]
I'll put them both in, and you can take your pick in situ.

| Icon | Name | Icon | Name 
| :--- | :--- | :--- | :--- |
| ![hue:adore-alt](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/adore-alt.svg)| hue:adore-alt | ![hue:adore](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/adore.svg)| hue:adore |

**Comment by clipse2004** [comment]
Holy shit nice that was fast :) 
Sorry was sleeping.

Great work! Big thanks 

Von meinem iPhone gesendet

**Comment by arallsopp** [comment]
Lol. No worries. Bed time here too, now :)

**Comment by arallsopp** [comment]
Hey @clipse2004.

Just to let you know, I'm going to be stopping development effort on this for a while, as my work is being stolen by [another repo](https://github.com/elax46/custom-brand-icons/releases) without permission, in breach of the CC license, and without any attempt to give credit to the original author or those who've helped me.

You'll doubltless recognise the icons I created specificlaly for you [here](https://github.com/elax46/custom-brand-icons/releases/tag/1.0.16). 

This project has always been offered as free to use, and for the benefit of the home assistant community rather than any individual. More than half of this library is the 80 or so original icons I've created, drawn and gifted to the home assistant community. Those icons are all original works, driven by requests from people like you, taken on as a willing task, and shared here on a non commercial basis for all who want them.

It felt good to give back, and the work was a reward in itself, but finding the icons I'm creating being offered elsewhere, proffered up alongside a request for paypal donations to support their creation is really not in the spirit of the community. 

The whole experience has left a bad taste in my mouth, and I'll be stepping away for some time.

Cheers, Marco.

Andy.
