### ISSUE TITLE
Philips HUE AMBIANCE WHITE EXPLORE Pendant Light white, 1-light source

### ISSUE THREAD

**Issue by srandal1s** [arallsopp/hass-hue-icons#34]
**What is the specific model of hue fixture/bulb that you want an icon for**
Philips HUE AMBIANCE WHITE EXPLORE Pendant Light white, 1-light source, Remote control

**Provide a URL that points to an image of this fixture/bulb**
https://www.illumination.co.uk/philips-hue-ambiance-white-explore-pendant-light-8718696168844.html?gclid=CjwKCAjw092IBhAwEiwAxR1lRq8T9aloqSJ2sNNRFyFF7TRN6J8z30kpE0rbxNGAoaqPtJi8oacq4RoCKT0QAvD_BwE

**Additional context**
Thanks man.

**Comment by arallsopp** [comment]
Its coming.

I've seen that shape on the hue home page under their floor lamps, but have never managed to find it before. Now I know its called Explore. Is it just this one, or is there a wall version you need?

![image](https://user-images.githubusercontent.com/2462104/129462617-4f8ab522-2762-4209-b6f4-b54be95d2aba.png)

**Comment by arallsopp** [comment]
Added. It'll be in the next release.

| Icon | Name |
| :--- | :--- | 
| ![hue:ceiling-explore](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-explore.svg)| hue:ceiling-explore |

**Comment by arallsopp** [comment]
Hey Sarah.

Just to let you know, I'm going to be stopping development effort on this for a while, as my work is being stolen by [another repo](https://github.com/elax46/custom-brand-icons/releases) without permission, in breach of the CC license, and without any attempt to give credit to the original author or those who've helped me.

Your issue duplicates an icon request made there, and the icon I created for you has been stolen and [sold on](https://github.com/elax46/custom-brand-icons/issues/29). 

This project has always been offered as free to use, and for the benefit of the home assistant community rather than any individual. More than half of this library is the 80 or so original icons I've created, drawn and gifted to the home assistant community. Those icons are all original works, driven by requests from people like you, taken on as a willing task, and shared here on a non commercial basis for all who want them.

It felt good to give back, and the work was a reward in itself, but finding the icons I'm creating being offered elsewhere, proffered up alongside a request for paypal donations to support their creation is really not in the spirit of the community. 

The whole experience has left a bad taste in my mouth, and I'll be stepping away for some time.

Cheers,

Andy.
