### ISSUE TITLE
Bulb group sultan lightstrip

### ISSUE THREAD

**Issue by jrspowers** [arallsopp/hass-hue-icons#35]
I still have a question, could you also make an off version of the hue:bulb-group-sultan-lightstrip that I would like to use on photo if everything turns out that there is a line through it and turns red? Thanks in advance![image](https://user-images.githubusercontent.com/60328474/129462607-6aba5131-fe55-4758-b67b-b70a91caa235.jpeg)

**Comment by arallsopp** [comment]
If I get into crossed out lights, then I imagine I'll need to double my icon set for crossed versions of everything. Also, that ledstrip sultan is already quite busy. Not sure a cross version will work. Are you trying to indicate the light group as off? I imagine there is way to switch the icon colour automatically for that state?

What *could* work is a non shaded version of that combination. Taking the bulb top to an outline would make it 'off'. I'll take a look at that.

**Comment by arallsopp** [comment]
How about the below: 
![image](https://user-images.githubusercontent.com/2462104/129473731-7b839161-54f3-4c6c-b8ba-8def2b3afdc0.png)

Its mostly in keeping with the hue icon set, and if toggled against the filled version would denote the appliances were off. Its akin to what I've done with hue:beyond.

**Comment by jrspowers** [comment]
yes I mean a line through the icons that you can clearly see that all the lights are off like this icon look at picture that would be very nice if that works ?![image](https://user-images.githubusercontent.com/60328474/129473936-1e8dbe7a-f717-4e60-97e3-53df1efa7d05.jpeg)

**Comment by arallsopp** [comment]
OK. You win. 

Added bulb-group-sultan-lightstrip-off to v.1.0.59 :)

| Icon | Name | 
| :--- | :--- |
 | ![hue:bulb-group-sultan-lightstrip](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-sultan-lightstrip-off.svg)| hue:bulb-group-sultan-lightstrip-off |

**Comment by jrspowers** [comment]
thank you man and how can i win this is really nice of you that you made this!

**Comment by arallsopp** [comment]
Hey @jrspowers .

Just to let you know, I'm going to be stopping development effort on this for a while, as my work is being stolen by [another repo](https://github.com/elax46/custom-brand-icons/releases) without permission, in breach of the CC license, and without any attempt to give credit to the original author or those who've helped me.

This project has always been offered as free to use, and for the benefit of the home assistant community rather than any individual. More than half of this library is the 80 or so original icons I've created, drawn and gifted to the home assistant community. Those icons are all original works, driven by requests from people like you, taken on as a willing task, and shared here on a non commercial basis for all who want them.

It felt good to give back, and the work was a reward in itself, but finding the icons I'm creating being offered elsewhere, proffered up alongside a request for paypal donations to support their creation is really not in the spirit of the community. 

The whole experience has left a bad taste in my mouth, and I'll be stepping away for some time.

Cheers,

Andy.

**Comment by jrspowers** [comment]
Hey @arallsopp 

unfortunate that there are people who do this without your permission wall you are the administrator of these icons and people are just going to abuse it & too bad you will be less active here for a while but understand your choices very much so hopefully see you  fast !
