### ISSUE TITLE
fugato lights

### ISSUE THREAD

**Issue by kalmma** [arallsopp/hass-hue-icons#37]
_If there is a specific hue fixture or bulb that you want an icon for, let me know and I will try to create it for you and add it to this pack._

Hue Fugato 2,3 and 4 spots

Be as specific as you can, as Philips often seem to have product family names where multiple variants exist under the same description.

https://www.philips-hue.com/nl-be/p/hue-white-and-color-ambiance-fugato-2-lichts-spotbalk/5063231P7

https://www.philips-hue.com/nl-be/p/hue-white-and-color-ambiance-fugato-3-lichts-spotbalk/5063331P7

https://www.philips-hue.com/nl-be/p/hue-white-and-color-ambiance-fugato-4-lichts-spotbalk/5063431P7

Preferably Philips' photography, as they use a consistent angle.

**Additional context**

Add any other context for your icon request here.

**Comment by arallsopp** [comment]
Thanks for the suggestion. I'll take a run at the two and three light fixtures first. The four is going to be hard to fit into a 24px block as its wide.

**Comment by arallsopp** [comment]
This will be the basis of the two lamp version. I needed to compress the width of the base unit a touch to make it fit :)

![image](https://user-images.githubusercontent.com/2462104/129496609-35ccb7f6-5569-48c2-9b8a-d06edfce3b54.png)

**Comment by arallsopp** [comment]
..and the three way 
![image](https://user-images.githubusercontent.com/2462104/129497274-53d396c2-9389-44f3-9fe7-4dd125873407.png)

**Comment by arallsopp** [comment]
Just about the only way I can squeeze all 4 onto the bar  :)
![image](https://user-images.githubusercontent.com/2462104/129497652-318a546d-5d35-4afd-88cd-3bdeb9c59e61.png)

I'll create a new release with these in shortly.

**Comment by arallsopp** [comment]
| Icon | Name |
| :--- | :--- | 
| ![hue:ceiling-fugato-two](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-fugato-two.svg)| hue:ceiling-fugato-two |
| ![hue:ceiling-fugato-three](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-fugato-three.svg)| hue:ceiling-fugato-three |
| ![hue:ceiling-fugato-four](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-fugato-four.svg)| hue:ceiling-fugato-four |

Thanks @kalmma for the suggestion.

**Comment by arallsopp** [comment]
Hey. Quick question. Didn't really stop to think that the bulbs on those pics (which were dark) should really be the lightest bit of the icon.

Should I maybe redo them to match the below?

![image](https://user-images.githubusercontent.com/2462104/129498384-e4237a91-66ca-4780-9542-168c9eac25e0.png)

**Comment by arallsopp** [comment]
Inverted the colours and kept the old versions as -alt variants:

| Icon | Name |
| :--- | :--- | 
| ![hue:ceiling-fugato-two](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-fugato-two.svg)| hue:ceiling-fugato-two |
| ![hue:ceiling-fugato-three](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-fugato-three.svg)| hue:ceiling-fugato-three |
| ![hue:ceiling-fugato-four](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-fugato-four.svg)| hue:ceiling-fugato-four |
| ![hue:ceiling-fugato-two-alt](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-fugato-two-alt.svg)| hue:ceiling-fugato-two-alt |
| ![hue:ceiling-fugato-three-alt](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-fugato-three-alt.svg)| hue:ceiling-fugato-three-alt |
| ![hue:ceiling-fugato-four-alt](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-fugato-four-alt.svg)| hue:ceiling-fugato-four-alt |

Thanks again, @kalmma. All done now.

**Comment by arallsopp** [comment]
Hey @kalmma. Your fugato icons are in, but I'm going to be stopping development effort on this for a while, as my work is being stolen by [another repo](https://github.com/elax46/custom-brand-icons/releases/tag/1.0.18) without permission, in breach of the CC license, and without any attempt to give credit to the original author or those who've helped me.

This project has always been offered as free to use, and for the benefit of the home assistant community rather than any individual. More than half of this library is the 80 or so original icons I've created, drawn and gifted to the home assistant community. Those icons are all original works, driven by requests from people like you, taken on as a willing task, and shared here on a non commercial basis for all who want them.

It felt good to give back, and the work was a reward in itself, but finding the icons I'm creating being offered elsewhere, proffered up alongside a request for paypal donations to support their creation is really not in the spirit of the community. 

The whole experience has left a bad taste in my mouth, and I'll be stepping away for some time.

Cheers,

Andy.
