### ISSUE TITLE
Request Icons

### ISSUE THREAD

**Issue by Git2689** [arallsopp/hass-hue-icons#39]
Hello Andy,

great work!!!!!

I have three proposals

Buratto Spot 3er
https://www.philips-hue.com/de-de/p/hue-white-ambiance-buratto-dreierspot/5046331P7 

Buratto Spot 4er
https://www.philips-hue.com/de-de/p/hue-white-ambiance-buratto-viererspot/5046431P7

TV
https://www.philips.de/c-e/so/fernseher/ambilight

Best Regards
Dirk

**Comment by arallsopp** [comment]
Morning @Git2689.

The ambilight TV is probably better handled by one of the existing set of custom icons.

| Icon | Name | Icon | Name 
| :--- | :--- | :--- | :--- |
| ![hue:gradient-lightstrip-wrap](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/gradient-lightstrip-wrap.svg)| hue:gradient-lightstrip-wrap | ![hue:gradient-lightstrip](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/gradient-lightstrip.svg)| hue:gradient-lightstrip |
| ![hue:lightstrip-tv-alt](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/lightstrip-tv-alt.svg)| hue:lightstrip-tv-alt | ![hue:lightstrip-tv](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/lightstrip-tv.svg)| hue:lightstrip-tv |
| ![hue:lightstrip-wrap](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/lightstrip-wrap.svg)| hue:lightstrip-wrap |

The buratto look a lot like the fugato I've just added, but if I can make icons look suitably different, I'll put something together. Could be that I just treat them as a row of repeating lamp shapes, as the 3 strip is not mounted in a circle.

| Icon | Name |
| :--- | :--- | 
| ![hue:ceiling-fugato-two](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-fugato-two.svg)| hue:ceiling-fugato-two |
| ![hue:ceiling-fugato-three](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-fugato-three.svg)| hue:ceiling-fugato-three |
| ![hue:ceiling-fugato-four](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-fugato-four.svg)| hue:ceiling-fugato-four |

Thanks for the suggestions, Dirk. Watch this space. :)

**Comment by arallsopp** [comment]
I'm thinking of going for the buratto as a single, double, triple and quadruple, based around this:

![image](https://user-images.githubusercontent.com/2462104/129544082-1deed441-2c92-4789-ae73-10c9805881c5.png)

**Comment by arallsopp** [comment]
Bit of tweaking with line weights, but I think this will work. They'll be in the next release:

![image](https://user-images.githubusercontent.com/2462104/129545488-d32fc2de-ed07-4688-9938-d5aff8e32d48.png)

**Comment by arallsopp** [comment]
Here's the final versions. Ready to go into 1.0.62

| Icon | Name |
| :--- | :--- | 
| ![hue:ceiling-buratto](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-buratto.svg)| hue:ceiling-buratto |
| ![hue:ceiling-buratto-two](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-buratto-two.svg)| hue:ceiling-buratto-two |
| ![hue:ceiling-buratto-three](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-buratto-three.svg)| hue:ceiling-buratto-three |
| ![hue:ceiling-buratto-four](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-buratto-four.svg)| hue:ceiling-buratto-four |

**Comment by Git2689** [comment]
Wow, very cool! Thanks a lot!
Do have an unique icon für TVs?

**Comment by arallsopp** [comment]
Hey Dirk.

I think hue:lightstrip-tv is as close as we will get for a while. 

![hue:lightstrip-tv](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/lightstrip-tv.svg)

Your buratto icons are in 1.0.62, but I'm afraid going to be stopping development effort on this for a while, as my work is being stolen by [another repo](https://github.com/elax46/custom-brand-icons/releases) without permission, in breach of the CC license, and without any attempt to give credit to the original author or those who've helped me.

This project has always been offered as free to use, and for the benefit of the home assistant community rather than any individual. More than half of this library is the 80 or so original icons I've created, drawn and gifted to the home assistant community. Those icons are all original works, driven by requests from people like you, taken on as a willing task, and shared here on a non commercial basis for all who want them.

It felt good to give back, and the work was a reward in itself, but finding the icons I'm creating being offered elsewhere, proffered up alongside a request for paypal donations to support their creation is really not in the spirit of the community. 

The whole experience has left a bad taste in my mouth, and I'll be stepping away for some time.

Cheers,

Andy.

**Comment by Git2689** [comment]
HI Andy,

bad to hear, bad thank you to for your great work!

Cheers
Dirk
