### ISSUE TITLE
Icons not showing in Android app

### ISSUE THREAD

**Issue by MPowerData** [arallsopp/hass-hue-icons#61]
Hi,

Somehow, some of the hue icons are not showing within the android application, while other hue icons do.

Create them on web lovelace ui.
Open Android app.
Icons don't show up.
Clearing app cache does not solve the problem.

Expected behavior
All icons showing, not just some

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Android 12

**Comment by arallsopp** [comment]
Thanks for raising this. I think there’s a related issue in #58, which also affects Android devices. I’ll try to get hold of an appropriate handset to test against. 

When I’ve seen it discussed on Reddit, et al, the issue seems to extend to all icon plugins so I’m not sure if it’s something we are doing wrong, or something that’s changed in HA, or both.

**Comment by MPowerData** [comment]
Yes, that seems very much related. The strange thing is, reloading the UI will show the icons. Closing the app and re-opening, and the icons below are not showing.

Someone mentioned:
More than likely the self made icons need an update to support better caching to work with android webview.

But is this something you can do?

**Comment by arallsopp** [comment]
Thanks for this. Am unsure. There are a few repos with the issue so I’ll look around and see if anyone has a fix. 

A lot of it is handled by home assistant with us just providing a script. If HA calls that script, it seems it works. If HA doesn’t call the script, it’s out of scope for a fix on this end. 

Hopefully there’s some wiggle room to play in, else I’m a bit stuck.

**Comment by MPowerData** [comment]
Yeah, it appears to be more generic. Custom brand icons has the same issue.

Thanks for looking in!

**Comment by arallsopp** [comment]
I'd expect that. That particular repo scrapes this one for the vast bulk of its content 😄

**Comment by MPowerData** [comment]
Haha, that explains...

I do have to say that it also sometimes happens in the web gui.

**Comment by arallsopp** [comment]
If you're getting it on desktop, please double check you have the 

```
frontend:
  extra_module_url:
    - /hacsfiles/hass-hue-icons/hass-hue-icons.js
```

line in your configuration.yaml. Omitting that can make the icons only show after navigation.

**Comment by MPowerData** [comment]
Thanks, I've added it, as it was not there...

**Comment by arallsopp** [comment]
Good work. Don't imagine you'll see misbehaviour in the desktop views again, but ping if you do :)

**Comment by arallsopp** [comment]
Darn. I've been looking into how I might make this an integration rather than a plugin, as it's been suggested that the former might be a way around the android app cache problem. 

Nope. Even the mighty [thomasloven's icon integration](https://github.com/thomasloven/hass-fontawesome/issues/42) has the same problem.  

- [ ] If even they can't solve it, I suspect I'm way out of my depth! I  suspect the HA front end team will need to assist before a resolution is found.

**Comment by MPowerData** [comment]
Yeah, let's hope we can get some support from them...

**Comment by arallsopp** [comment]
Howdo @MPowerData. 

Assuming you've updated to Core 2021.11.1, and updated [hass-hue-icons ](https://github.com/arallsopp/hass-hue-icons) to any of the 1.1.x releases, I was wondering whether you might find the issue now resolved? I tracked some misbehaviour to an oddity around exposure of the frontendversion variable, and by deprecating the legacy support for very old versions, hass-hue-icons will now load the modern version of the icons by default. If the picker support is detected, that gets added too, but even if the variable is missing, you should still get the icons. Not sure if that's related to the android issue, but let me know if the problem persists?

**Comment by MPowerData** [comment]
Hi,

Thank you for your continuous support.

I can indeed confirm that the problem is solved, really nice to see!

Thanks again for your work!

**Comment by arallsopp** [comment]
Awesome. So glad to hear that. Excellent news.
