### ISSUE TITLE
 Philips Hue Impress 17434

### ISSUE THREAD

**Issue by Bolgath** [arallsopp/hass-hue-icons#66]
_If there is a specific hue fixture or bulb that you want an icon for, let me know and I will try to create it for you and add it to this pack._

**What is the specific model of hue fixture/bulb that you want an icon for**

 Philips Hue Impress 17434

**Provide a URL that points to an image of this fixture/bulb**

https://www.philips-hue.com/sv-se/p/hue-white-and-color-ambiance-impress-piedestallampa-for-utomhusbruk/1743430P7

**Additional context**

Add any other context for your icon request here.

**Comment by arallsopp** [comment]
Glad I saw this, as that's probably how I was going to style issue #65. OK. On it.

**Comment by arallsopp** [comment]
I'm thinking along the lines of the classic hue icons (eg: taking the angles and rounded corners from things like group ceiling square ![image](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-ceiling-square.svg) and using them here. I think trying to do a stylised representation is going to be easier than a likeness of the actual geometry, as the pillars will otherwise get too tall and skinny.

![image](https://user-images.githubusercontent.com/2462104/134765513-6c66d11c-3116-40b0-9ffd-9224482cb94e.png)

**Comment by arallsopp** [comment]
Added in v.1.0.89. Thanks again, @Bolgath for the suggestion.

| Icon | Name |
| :--- | :--- |
| ![hue:pillar-impress](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/pillar-impress.svg)| hue:pillar-impress|
| ![hue:pillar-impress-short](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/pillar-impress-short.svg)| hue:pillar-impress-short|
