### ISSUE TITLE
Tuar wall  and standing lights

### ISSUE THREAD

**Issue by Mariusthvdb** [arallsopp/hass-hue-icons#9]
_If there is a specific hue fixture or bulb that you want an icon for, let me know and I will try to create it for you and add it to this pack._

**What is the specific model of hue fixture/bulb that you want an icon for**

Tuar lights: https://www.beaumotica.nl/philips-hue-outdoor-tuar

Be as specific as you can, as Philips often seem to have product family names where multiple variants exist under the same description.

**Provide a URL that points to an image of this fixture/bulb**

Preferably Philips' photography, as they use a consistent angle.

**Additional context**

Add any other context for your icon request here.

**Comment by arallsopp** [comment]
The wall light and short pillar look doable. The very tall one might be a bit of a pain. Will take a run at it.

**Comment by Mariusthvdb** [comment]
cool, would be awesome!

Note the hue app installed bollard for it ;-) the standing light that is, no icon for the wall light

**Comment by arallsopp** [comment]
Good call! 

Wall light will be in v.1.0.27.  The short bollard will follow.

![image](https://user-images.githubusercontent.com/2462104/126033274-79288d2e-9e82-4214-9c35-ba4213ab504f.png)

**Comment by arallsopp** [comment]
So much curve! Couldn't just re-use the wall one and stick it on a pole as the line weights would be off :)

Its coming....
![image](https://user-images.githubusercontent.com/2462104/126033670-f14cf75b-2241-40a3-a429-3c971fe3be0f.png)

**Comment by arallsopp** [comment]
Closed in v.1.0.27

| Icon | Name | Icon | Name 
| :--- | :--- | :--- | :--- |
| ![hue:pillar-tuar](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/pillar-tuar.svg)| hue:pillar-tuar | ![hue:wall-tuar](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/wall-tuar.svg)| hue:wall-tuar |

**Comment by arallsopp** [comment]
@Mariusthvdb: let me know if you have any issues.

**Comment by arallsopp** [comment]
Hey @Mariusthvdb.

Just to let you know, I'm going to be stopping development effort on this for a while, as my work is being stolen by [another repo](https://github.com/elax46/custom-brand-icons/) without permission, in breach of the CC license, and without any attempt to give credit to the original author or those who've helped me.

This project has always been offered as free to use, and for the benefit of the home assistant community rather than any individual. More than half of this library is the 80 or so original icons I've created, drawn and gifted to the home assistant community. Those icons are all original works, driven by requests from people like you, taken on as a willing task, and shared here on a non commercial basis for all who want them.

It felt good to give back, and the work was a reward in itself, but finding the icons I'm creating being offered elsewhere, proffered up alongside a request for paypal donations to support their creation is really not in the spirit of the community. 

The whole experience has left a bad taste in my mouth, and I'll be stepping away for some time.

Cheers, and thanks for your interest.

Andy.

**Comment by Mariusthvdb** [comment]
yeah, I see, thats not the spirit we tend to share our efforts. I'll post a remark considering that on the repo you mention.

Thanks for your work, and I hope this gets settled as it should be soon.
